import React from "react";

function Homepage() {
  return (
    <div>
      <h1>Homepage</h1>
      <p>
        This page is generated by{" "}
        <span style={{ color: "red", fontWeight: "bold" }}>
          gatsby-theme-demo
        </span>
        .
      </p>
      <p>v 15</p>
    </div>
  );
}

export default Homepage;
